# Netlify configuration for AI SEO Automation Platform

[build]
  # Build command - using Vite to build the production files
  command = "npm run build"
  
  # Publish directory - where the built files are located
  publish = "dist"

# Redirect all routes to index.html for single-page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for production (optional - users provide their own API keys)
[build.environment]
  NODE_VERSION = "18"

# Cache settings for better performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
